import type { OrganId } from "./anatomy-data";

export interface AnatomyFact {
  id: string;
  headline: string;
  fact: string;
  category: FactCategory;
  organId?: OrganId;
  organName?: string;
  badge: "Mind-Blowing" | "Clinical Pearl" | "Superpower" | "Deep Biology" | "Fun Fact" | "Record";
  icon: string;
}

export type FactCategory =
  | "All"
  | "Cardiovascular"
  | "Brain & Nerves"
  | "Respiratory"
  | "Digestive"
  | "Bones & Muscles"
  | "Sensory & Eyes"
  | "Skin & Integumentary"
  | "Kidneys & Excretory"
  | "Blood & Immune"
  | "Records & Curiosities";

export const FACT_CATEGORIES: FactCategory[] = [
  "All",
  "Cardiovascular",
  "Brain & Nerves",
  "Respiratory",
  "Digestive",
  "Bones & Muscles",
  "Sensory & Eyes",
  "Skin & Integumentary",
  "Kidneys & Excretory",
  "Blood & Immune",
  "Records & Curiosities",
];

export const DID_YOU_KNOW_DATABASE: AnatomyFact[] = [
  // ==================== CARDIOVASCULAR (1-12) ====================
  {
    id: "cardio-1",
    headline: "100,000 Beats Every Single Day",
    fact: "Your heart contracts roughly 100,000 times a day (about 35 million beats a year), pumping roughly 7,500 liters (2,000 gallons) of oxygenated blood through your circulatory system daily.",
    category: "Cardiovascular",
    organId: "heart",
    organName: "Heart",
    badge: "Record",
    icon: "❤️",
  },
  {
    id: "cardio-2",
    headline: "60,000 Miles of Blood Vessels",
    fact: "If laid end to end, the blood vessels (arteries, veins, and capillaries) in an adult human body would measure over 60,000 miles (96,500 km)—enough to encircle the Earth more than two and a half times.",
    category: "Cardiovascular",
    organId: "heart",
    organName: "Vascular Tree",
    badge: "Mind-Blowing",
    icon: "🩸",
  },
  {
    id: "cardio-3",
    headline: "An Independent Heartbeat",
    fact: "Because the heart generates its own electrical impulses via the Sinoatrial (SA) node, it can continue to beat outside the body as long as it receives an adequate supply of oxygen.",
    category: "Cardiovascular",
    organId: "heart",
    organName: "SA Node",
    badge: "Clinical Pearl",
    icon: "⚡",
  },
  {
    id: "cardio-4",
    headline: "The Blue Whale Scale",
    fact: "Over an average lifetime of 75 years, the human heart pumps roughly 200 million liters of blood—enough to fill over 3 supertankers or 80 Olympic swimming pools.",
    category: "Cardiovascular",
    organId: "heart",
    organName: "Myocardium",
    badge: "Record",
    icon: "🏊",
  },
  {
    id: "cardio-5",
    headline: "Pressure to Squirt 30 Feet",
    fact: "The left ventricle contracts with enough hydraulic force that it creates roughly 120 mmHg of pressure, capable of spurting blood up to 30 feet in the air if severed.",
    category: "Cardiovascular",
    organId: "heart",
    organName: "Left Ventricle",
    badge: "Mind-Blowing",
    icon: "💥",
  },
  {
    id: "cardio-6",
    headline: "The Aorta: Garden Hose of the Body",
    fact: "The aorta is the largest artery in the human body, with a diameter of about 2.5 to 3 cm (about the thickness of a garden hose) handling the direct peak pressure output of the left ventricle.",
    category: "Cardiovascular",
    organId: "heart",
    organName: "Aorta",
    badge: "Deep Biology",
    icon: "🫀",
  },
  {
    id: "cardio-7",
    headline: "One Minute Full Circulation",
    fact: "It takes only about 60 seconds for a single red blood cell to complete an entire circuit through your cardiovascular tree from the heart, out to the toes, and back.",
    category: "Cardiovascular",
    organId: "heart",
    organName: "Erythrocytes",
    badge: "Superpower",
    icon: "⏱️",
  },
  {
    id: "cardio-8",
    headline: "Heart Strings are Real Anatomy",
    fact: "The heart literally contains 'heart strings' called chordae tendineae—tough, fibrous cords that tether the tricuspid and mitral valve leaflets to papillary muscles to prevent prolapse.",
    category: "Cardiovascular",
    organId: "heart",
    organName: "Chordae Tendineae",
    badge: "Fun Fact",
    icon: "🎻",
  },
  {
    id: "cardio-9",
    headline: "The Only Avascular Structure",
    fact: "The cornea of the eye is the only tissue in the human body that receives zero direct blood supply; it absorbs oxygen directly from the surrounding air.",
    category: "Cardiovascular",
    organId: "eyeball",
    organName: "Cornea",
    badge: "Clinical Pearl",
    icon: "👁️",
  },
  {
    id: "cardio-10",
    headline: "Capillaries are Single-File Tollways",
    fact: "Capillaries are so narrow (5 to 10 micrometers) that red blood cells (which are ~7.5 micrometers) must squeeze through them in single file, deforming their biconcave shape.",
    category: "Cardiovascular",
    organId: "heart",
    organName: "Capillaries",
    badge: "Deep Biology",
    icon: "🔬",
  },
  {
    id: "cardio-11",
    headline: "Higher Blood Pressure in Giraffe Humans",
    fact: "When standing, the blood pressure in your feet is about 100 mmHg higher than at your heart due to hydrostatic gravitational column weight.",
    category: "Cardiovascular",
    organId: "heart",
    organName: "Venous System",
    badge: "Clinical Pearl",
    icon: "🦵",
  },
  {
    id: "cardio-12",
    headline: "Heart Muscle Never Fatigues",
    fact: "Cardiac muscle fibers contain nearly 40% mitochondria by volume (compared to only 2-8% in skeletal muscle), ensuring they run purely aerobically without accumulating lactic acid fatigue.",
    category: "Cardiovascular",
    organId: "heart",
    organName: "Cardiomyocytes",
    badge: "Superpower",
    icon: "🔋",
  },

  // ==================== BRAIN & NERVES (13-25) ====================
  {
    id: "neuro-13",
    headline: "86 Billion Neurons",
    fact: "The human brain contains approximately 86 billion neurons and over 100 trillion synaptic connections—more connections than there are stars in the entire Milky Way galaxy.",
    category: "Brain & Nerves",
    organId: "brain",
    organName: "Cerebral Cortex",
    badge: "Mind-Blowing",
    icon: "🧠",
  },
  {
    id: "neuro-14",
    headline: "20 Watts of Constant Power",
    fact: "The human brain operates on approximately 20 watts of electrical power—enough to illuminate a dim LED lightbulb while executing calculations no supercomputer can match.",
    category: "Brain & Nerves",
    organId: "brain",
    organName: "Brain",
    badge: "Superpower",
    icon: "💡",
  },
  {
    id: "neuro-15",
    headline: "The Brain Feels No Pain",
    fact: "The brain parenchyma has no nociceptors (pain receptors). Brain surgeries can be performed on awake patients while they speak or play instruments; only the surrounding meninges feel pain.",
    category: "Brain & Nerves",
    organId: "brain",
    organName: "Meninges",
    badge: "Clinical Pearl",
    icon: "🩺",
  },
  {
    id: "neuro-16",
    headline: "Nerve Impulses at 268 MPH",
    fact: "Alpha motor nerve impulses travel down myelinated neurons at speeds up to 268 miles per hour (430 km/h)—faster than a Formula 1 racing car.",
    category: "Brain & Nerves",
    organId: "brain",
    organName: "Myelin Sheath",
    badge: "Record",
    icon: "🏎️",
  },
  {
    id: "neuro-17",
    headline: "20% of Oxygen for 2% of Weight",
    fact: "Although your brain accounts for only about 2% of your total body mass, it consumes roughly 20% of your body's total oxygen and glucose supply.",
    category: "Brain & Nerves",
    organId: "brain",
    organName: "Cerebral Metabolism",
    badge: "Deep Biology",
    icon: "🔥",
  },
  {
    id: "neuro-18",
    headline: "60% Pure Fat",
    fact: "The human brain is the fattest organ in the body, consisting of nearly 60% lipids, largely structural phospholipids and DHA essential for neural membrane fluidity.",
    category: "Brain & Nerves",
    organId: "brain",
    organName: "Lipid Matrix",
    badge: "Fun Fact",
    icon: "🧈",
  },
  {
    id: "neuro-19",
    headline: "The Glymphatic Night Shift",
    fact: "While you sleep, cerebrospinal fluid rushes through brain tissue via the glymphatic system, clearing out metabolic waste products including amyloid-beta plaques.",
    category: "Brain & Nerves",
    organId: "brain",
    organName: "Glymphatic System",
    badge: "Clinical Pearl",
    icon: "🌙",
  },
  {
    id: "neuro-20",
    headline: "Cerebellum Holds 80% of Neurons",
    fact: "The cerebellum accounts for only 10% of total brain volume, yet it packs over 50 billion neurons—more than 50% of the entire brain's neuronal count.",
    category: "Brain & Nerves",
    organId: "brain",
    organName: "Cerebellum",
    badge: "Mind-Blowing",
    icon: "🎯",
  },
  {
    id: "neuro-21",
    headline: "70,000 Thoughts a Day",
    fact: "Cognitive neuroscientists estimate that the human brain processes between 50,000 to 70,000 spontaneous thoughts in a single 24-hour cycle.",
    category: "Brain & Nerves",
    organId: "brain",
    organName: "Frontal Lobe",
    badge: "Fun Fact",
    icon: "💭",
  },
  {
    id: "neuro-22",
    headline: "The Vagus Nerve: Brain-Body Superhighway",
    fact: "The tenth cranial nerve (Vagus) wanders from the brainstem all the way down to the colon, regulating heart rate, digestive enzymes, and parasympathetic calm.",
    category: "Brain & Nerves",
    organId: "brain",
    organName: "Cranial Nerve X",
    badge: "Deep Biology",
    icon: "🧘",
  },
  {
    id: "neuro-23",
    headline: "Neuroplasticity Never Truly Stops",
    fact: "Even into late adulthood, the human hippocampus undergoes adult neurogenesis, generating thousands of new functional neurons every day.",
    category: "Brain & Nerves",
    organId: "brain",
    organName: "Hippocampus",
    badge: "Superpower",
    icon: "🌱",
  },
  {
    id: "neuro-24",
    headline: "10,000 Synapses Per Single Neuron",
    fact: "A single Purkinje cell in the cerebellar cortex can receive over 200,000 synaptic inputs from parallel fibers simultaneously, computing complex motor coordination.",
    category: "Brain & Nerves",
    organId: "brain",
    organName: "Purkinje Cell",
    badge: "Deep Biology",
    icon: "🌳",
  },
  {
    id: "neuro-25",
    headline: "Synesthesia: Blended Senses",
    fact: "In people with synesthesia, cross-talk between brain sensory areas causes them to 'taste words', 'see sounds in color', or feel numbers as distinct spatial personalities.",
    category: "Brain & Nerves",
    organId: "brain",
    organName: "Sensory Cortex",
    badge: "Fun Fact",
    icon: "🎨",
  },

  // ==================== RESPIRATORY SYSTEM (26-37) ====================
  {
    id: "resp-26",
    headline: "Tennis Court Sized Gas Exchange",
    fact: "Your lungs contain about 300 to 500 million microscopic alveoli. If spread flat, their combined surface area would cover roughly 70 to 100 square meters—the size of a tennis court.",
    category: "Respiratory",
    organId: "lungs",
    organName: "Alveoli",
    badge: "Mind-Blowing",
    icon: "🎾",
  },
  {
    id: "resp-27",
    headline: "Lungs are the Only Floating Organs",
    fact: "Because they contain millions of air-filled alveolar sacs, healthy human lungs are the only organs in the body that can float on water.",
    category: "Respiratory",
    organId: "lungs",
    organName: "Lungs",
    badge: "Fun Fact",
    icon: "⛵",
  },
  {
    id: "resp-28",
    headline: "The Asymmetrical Left Lung",
    fact: "Your left lung is about 10% smaller than your right lung (2 lobes vs 3 lobes) to make anatomic room (the cardiac notch) for the apex of your heart.",
    category: "Respiratory",
    organId: "lungs",
    organName: "Cardiac Notch",
    badge: "Clinical Pearl",
    icon: "🫁",
  },
  {
    id: "resp-29",
    headline: "22,000 Breaths Daily",
    fact: "The average adult takes between 12 and 20 breaths per minute, totaling roughly 22,000 breaths and moving over 11,000 liters (2,900 gallons) of air every day.",
    category: "Respiratory",
    organId: "lungs",
    organName: "Ventilation",
    badge: "Record",
    icon: "🌬️",
  },
  {
    id: "resp-30",
    headline: "Cilia Mucus Escalator",
    fact: "Billions of microscopic hair-like cilia beat 10 to 15 times per second in wave-like synchrony, constantly sweeping mucus, dust, and pathogens up the trachea into the throat.",
    category: "Respiratory",
    organId: "lungs",
    organName: "Mucociliary Escalator",
    badge: "Superpower",
    icon: "🧹",
  },
  {
    id: "resp-31",
    headline: "Sneezes Travel at 100 MPH",
    fact: "A human sneeze can expel irritants, droplets, and air from the nasal cavities at speeds exceeding 100 miles per hour (160 km/h) up to 25 feet away.",
    category: "Respiratory",
    organId: "lungs",
    organName: "Sneeze Reflex",
    badge: "Mind-Blowing",
    icon: "🤧",
  },
  {
    id: "resp-32",
    headline: "Losing Half a Liter of Water Breathing",
    fact: "Through standard respiration, humans exhale approximately 400 to 500 milliliters of pure water vapor every single day just by warming and humidifying inhaled air.",
    category: "Respiratory",
    organId: "lungs",
    organName: "Expired Gas",
    badge: "Fun Fact",
    icon: "💧",
  },
  {
    id: "resp-33",
    headline: "Surfactant Prevents Lung Collapse",
    fact: "Type II alveolar cells secrete pulmonary surfactant—a lipid-protein mixture that reduces water surface tension, preventing your alveoli from collapsing during expiration.",
    category: "Respiratory",
    organId: "lungs",
    organName: "Type II Pneumocytes",
    badge: "Clinical Pearl",
    icon: "🫧",
  },
  {
    id: "resp-34",
    headline: "The Nasal Cycle Switches Sides",
    fact: "Every 2 to 4 hours, your autonomic nervous system automatically switches airflow congestion between your left and right nostrils through alternating erectile tissue swelling.",
    category: "Respiratory",
    organId: "lungs",
    organName: "Nasal Turbinates",
    badge: "Fun Fact",
    icon: "👃",
  },
  {
    id: "resp-35",
    headline: "Diaphragm: The Primary Engine",
    fact: "The dome-shaped diaphragm contracts downward during inhalation, creating negative intrathoracic pressure that pulls air into the lungs like a biological piston.",
    category: "Respiratory",
    organId: "lungs",
    organName: "Diaphragm",
    badge: "Deep Biology",
    icon: "⚙️",
  },
  {
    id: "resp-36",
    headline: "Coughing Air Speed Record",
    fact: "A vigorous cough produces air velocities approaching Mach 0.1 (~70-80 mph), clearing obstructions from the subglottic airway with acoustic shockwaves.",
    category: "Respiratory",
    organId: "lungs",
    organName: "Cough Reflex",
    badge: "Record",
    icon: "🗣️",
  },
  {
    id: "resp-37",
    headline: "Blood-Gas Barrier: 0.5 Microns",
    fact: "The respiratory membrane separating capillary blood from alveolar air is less than 0.5 micrometers thick—50 times thinner than a sheet of tissue paper.",
    category: "Respiratory",
    organId: "lungs",
    organName: "Blood-Gas Barrier",
    badge: "Deep Biology",
    icon: "🔬",
  },

  // ==================== DIGESTIVE SYSTEM & METABOLISM (38-50) ====================
  {
    id: "dig-38",
    headline: "Battery-Acid Strength Stomach Juice",
    fact: "Stomach hydrochloric acid has a pH of 1.5 to 2.0—strong enough to dissolve zinc metal and razor blades. A heavy mucus layer protects your gastric wall from auto-digestion.",
    category: "Digestive",
    organId: "intestine",
    organName: "Gastric Acid",
    badge: "Mind-Blowing",
    icon: "🧪",
  },
  {
    id: "dig-39",
    headline: "A Brand New Stomach Lining Every 3 Days",
    fact: "To prevent gastric self-digestion, stomach surface epithelial cells shed and completely replace themselves every 3 to 5 days through rapid mitotic stem cell turnover.",
    category: "Digestive",
    organId: "intestine",
    organName: "Gastric Epithelium",
    badge: "Superpower",
    icon: "🛡️",
  },
  {
    id: "dig-40",
    headline: "38 Trillion Gut Bacteria",
    fact: "Your digestive tract houses roughly 38 trillion bacterial cells representing over 1,000 species—roughly matching or outnumbering the human cells in your entire body.",
    category: "Digestive",
    organId: "intestine",
    organName: "Microbiome",
    badge: "Record",
    icon: "🦠",
  },
  {
    id: "dig-41",
    headline: "The Liver Can Fully Regenerate",
    fact: "The liver is the only human organ capable of full biological regeneration. As little as 25% of a healthy liver can regrow back to 100% of its original functional mass within months.",
    category: "Digestive",
    organId: "liver",
    organName: "Liver",
    badge: "Superpower",
    icon: "🔄",
  },
  {
    id: "dig-42",
    headline: "500 Discrete Liver Functions",
    fact: "The liver functions as the body's ultimate biochemical refinery, performing over 500 vital roles including bile synthesis, glycogen storage, toxin neutralization, and clotting factor production.",
    category: "Digestive",
    organId: "liver",
    organName: "Hepatocytes",
    badge: "Deep Biology",
    icon: "🏭",
  },
  {
    id: "dig-43",
    headline: "22 Feet of Small Intestine",
    fact: "Despite its name, the small intestine is approximately 20 to 22 feet (6 to 7 meters) long, with microvilli expanding its internal absorptive area to nearly 30 square meters.",
    category: "Digestive",
    organId: "intestine",
    organName: "Small Intestine",
    badge: "Record",
    icon: "📏",
  },
  {
    id: "dig-44",
    headline: "The 'Second Brain' in the Gut",
    fact: "The Enteric Nervous System (ENS) contains over 500 million neurons embedded throughout the digestive tract wall, operating semi-independently from the brain to manage peristalsis.",
    category: "Digestive",
    organId: "intestine",
    organName: "Enteric Plexus",
    badge: "Clinical Pearl",
    icon: "🧠",
  },
  {
    id: "dig-45",
    headline: "90% of Serotonin Made in the Gut",
    fact: "Over 90% of the body's serotonin ('the happiness molecule') is produced by enterochromaffin cells in your gut mucosa, where it regulates bowel motility and systemic mood.",
    category: "Digestive",
    organId: "intestine",
    organName: "Enterochromaffin Cells",
    badge: "Mind-Blowing",
    icon: "✨",
  },
  {
    id: "dig-46",
    headline: "1.5 Liters of Saliva Every Day",
    fact: "Human salivary glands (parotid, submandibular, and sublingual) produce 1.0 to 1.5 liters of saliva daily—enough over a lifetime to fill two average backyard swimming pools.",
    category: "Digestive",
    organId: "intestine",
    organName: "Salivary Glands",
    badge: "Fun Fact",
    icon: "🤤",
  },
  {
    id: "dig-47",
    headline: "Pancreas Dual Superpower",
    fact: "The pancreas is both an exocrine gland (secreting 1.5 L of bicarbonate digestive juices into the duodenum) and an endocrine organ (Islets of Langerhans making insulin and glucagon).",
    category: "Digestive",
    organId: "pancreas",
    organName: "Pancreas",
    badge: "Clinical Pearl",
    icon: "⚖️",
  },
  {
    id: "dig-48",
    headline: "Upside Down Swallowing",
    fact: "Thanks to coordinated peristaltic muscular waves in the esophagus, you can swallow food and water even while standing completely upside down on your head.",
    category: "Digestive",
    organId: "intestine",
    organName: "Esophagus",
    badge: "Fun Fact",
    icon: "🤸",
  },
  {
    id: "dig-49",
    headline: "Bile is Recycled 20 Times",
    fact: "Through the enterohepatic circulation, your liver secretes bile salts which are reabsorbed in the terminal ileum and recycled through the portal vein up to 20 times before excretion.",
    category: "Digestive",
    organId: "liver",
    organName: "Bile Cycle",
    badge: "Deep Biology",
    icon: "♻️",
  },
  {
    id: "dig-50",
    headline: "Gallbladder Concentrates Bile 10x",
    fact: "The gallbladder actively absorbs water and electrolytes to concentrate liver-produced bile by up to 10-fold before squeezing it into the duodenum upon eating fat.",
    category: "Digestive",
    organId: "liver",
    organName: "Gallbladder",
    badge: "Clinical Pearl",
    icon: "🫒",
  },

  // ==================== BONES, JOINTS & MUSCLES (51-64) ====================
  {
    id: "musc-51",
    headline: "Bone is Stronger Than Reinforced Concrete",
    fact: "Ounce for ounce, human cortical bone has a compressive strength greater than granite and four times stronger than reinforced concrete, capable of supporting 9 metric tons.",
    category: "Bones & Muscles",
    organId: "skin",
    organName: "Femur Bone",
    badge: "Mind-Blowing",
    icon: "🦴",
  },
  {
    id: "musc-52",
    headline: "Born with 270 Bones, Die with 206",
    fact: "Human infants are born with around 270 soft cartilaginous bones. As children develop, many bones fuse together (such as skull sutures and sacrum) leaving 206 adult bones.",
    category: "Bones & Muscles",
    organId: "skin",
    organName: "Skeleton",
    badge: "Fun Fact",
    icon: "👶",
  },
  {
    id: "musc-53",
    headline: "Half Your Bones are in Your Hands and Feet",
    fact: "Your hands (54 bones) and feet (52 bones) contain a combined 106 bones—more than half of all the 206 bones in the entire human skeleton.",
    category: "Bones & Muscles",
    organId: "skin",
    organName: "Carpals & Tarsals",
    badge: "Record",
    icon: "🖐️",
  },
  {
    id: "musc-54",
    headline: "The Masseter: Strongest Muscle by Weight",
    fact: "The jaw muscle (masseter) is the strongest muscle in the human body relative to its size, capable of exerting a molar biting force exceeding 200 pounds (90 kg).",
    category: "Bones & Muscles",
    organId: "skin",
    organName: "Masseter",
    badge: "Record",
    icon: "💪",
  },
  {
    id: "musc-55",
    headline: "The Smallest Bone: 3 Millimeters",
    fact: "The stapes (stirrup bone) in the middle ear is the smallest and lightest bone in the human body, measuring just 3 x 2.5 mm and weighing only a few milligrams.",
    category: "Bones & Muscles",
    organId: "skin",
    organName: "Stapes",
    badge: "Fun Fact",
    icon: "👂",
  },
  {
    id: "musc-56",
    headline: "The Only Floating Bone: Hyoid",
    fact: "The U-shaped hyoid bone in the anterior neck is the only bone in the human skeleton that does not articulate with any other bone; it is suspended purely by ligaments and muscles.",
    category: "Bones & Muscles",
    organId: "skin",
    organName: "Hyoid",
    badge: "Clinical Pearl",
    icon: "🧲",
  },
  {
    id: "musc-57",
    headline: "A Completely New Skeleton Every 10 Years",
    fact: "Through continuous remodeling by osteoclasts (bone resorption) and osteoblasts (bone formation), your entire skeleton is completely replaced with new mineralized tissue every decade.",
    category: "Bones & Muscles",
    organId: "skin",
    organName: "Osteoclasts & Osteoblasts",
    badge: "Superpower",
    icon: "⏳",
  },
  {
    id: "musc-58",
    headline: "Over 600 Skeletal Muscles",
    fact: "The human body contains more than 600 distinct skeletal muscles, making up roughly 40% of adult body weight and generating kinetic force and 85% of body heat.",
    category: "Bones & Muscles",
    organId: "skin",
    organName: "Muscular System",
    badge: "Record",
    icon: "🏋️",
  },
  {
    id: "musc-59",
    headline: "The Eye Muscles Move 100,000 Times a Day",
    fact: "The six extraocular muscles controlling eye saccades are the most active muscles in the human body, twitching more than 100,000 times in 24 hours.",
    category: "Bones & Muscles",
    organId: "eyeball",
    organName: "Extraocular Muscles",
    badge: "Record",
    icon: "👀",
  },
  {
    id: "musc-60",
    headline: "Taller in the Morning by 1 Centimeter",
    fact: "You are approximately 1 cm (0.4 inches) taller in the morning than at night because gravity compresses the gelatinous nucleus pulposus of intervertebral spinal discs during the day.",
    category: "Bones & Muscles",
    organId: "skin",
    organName: "Spinal Discs",
    badge: "Fun Fact",
    icon: "📏",
  },
  {
    id: "musc-61",
    headline: "Stapedius: The Smallest Muscle",
    fact: "Measuring just over 1 mm in length, the stapedius muscle in the middle ear contracts automatically to dampen deafening loud sounds and protect delicate hair cells.",
    category: "Bones & Muscles",
    organId: "skin",
    organName: "Stapedius",
    badge: "Clinical Pearl",
    icon: "🛡️",
  },
  {
    id: "musc-62",
    headline: "Femur Handles 30x Body Weight",
    fact: "The femur (thigh bone) is the longest, heaviest, and strongest bone in the body, capable of withstanding axial impact forces up to 30 times an adult's body weight.",
    category: "Bones & Muscles",
    organId: "skin",
    organName: "Femur",
    badge: "Record",
    icon: "⚡",
  },
  {
    id: "musc-63",
    headline: "Synovial Fluid: Slippier Than Wet Ice",
    fact: "The synovial fluid lubricating your knee and hip joints has a coefficient of friction of 0.001—making it about five times slicker than two wet ice cubes sliding against each other.",
    category: "Bones & Muscles",
    organId: "skin",
    organName: "Synovial Joints",
    badge: "Mind-Blowing",
    icon: "🧊",
  },
  {
    id: "musc-64",
    headline: "Gluteus Maximus: The Largest Muscle",
    fact: "The gluteus maximus is the largest and most massive single muscle in the human body, evolved specifically to maintain upright posture, run, and climb stairs.",
    category: "Bones & Muscles",
    organId: "skin",
    organName: "Gluteus Maximus",
    badge: "Fun Fact",
    icon: "🏃",
  },

  // ==================== SENSORY & EYES (65-75) ====================
  {
    id: "sens-65",
    headline: "576 Megapixel Resolution",
    fact: "If the human visual system were evaluated like a digital sensor, the human eye combined with cortical image processing possesses an equivalent resolution of roughly 576 megapixels.",
    category: "Sensory & Eyes",
    organId: "eyeball",
    organName: "Retina",
    badge: "Mind-Blowing",
    icon: "📸",
  },
  {
    id: "sens-66",
    headline: "10 Million Colors Distinct",
    fact: "Through three types of cone photoreceptors (S, M, and L opsins), the human retina can distinguish approximately 10 million distinct color variations and gradations.",
    category: "Sensory & Eyes",
    organId: "eyeball",
    organName: "Cone Photoreceptors",
    badge: "Superpower",
    icon: "🌈",
  },
  {
    id: "sens-67",
    headline: "28,000 Blinks Every Day",
    fact: "The average human blinks between 15 to 20 times per minute (nearly 28,000 blinks daily), spreading a tripartite tear film (lipid, aqueous, mucin) to nourish the cornea.",
    category: "Sensory & Eyes",
    organId: "eyeball",
    organName: "Tear Film",
    badge: "Fun Fact",
    icon: "👁️",
  },
  {
    id: "sens-68",
    headline: "Corneal Healing in 24 Hours",
    fact: "The corneal epithelium has one of the fastest regenerative rates in the human body; minor superficial scratches can fully heal and seal within 24 to 48 hours.",
    category: "Sensory & Eyes",
    organId: "eyeball",
    organName: "Corneal Epithelium",
    badge: "Clinical Pearl",
    icon: "✨",
  },
  {
    id: "sens-69",
    headline: "1 Trillion Distinct Scents",
    fact: "Research published in Science showed that the human olfactory system can discriminate over 1 trillion distinct olfactory scent combinations via 400 odorant receptor types.",
    category: "Sensory & Eyes",
    organId: "brain",
    organName: "Olfactory Bulb",
    badge: "Record",
    icon: "👃",
  },
  {
    id: "sens-70",
    headline: "Ears and Nose Never Stop Growing",
    fact: "Due to gravity and continuous collagen remodeling, human ears and the tip of the nose continue to slowly enlarge throughout your entire lifespan.",
    category: "Sensory & Eyes",
    organId: "skin",
    organName: "Cartilage",
    badge: "Fun Fact",
    icon: "👂",
  },
  {
    id: "sens-71",
    headline: "10,000 Taste Buds Replaced Every 2 Weeks",
    fact: "The human tongue has roughly 10,000 taste buds detecting five basic modalities (sweet, salty, sour, bitter, umami); each gustatory cell is replaced every 10 to 14 days.",
    category: "Sensory & Eyes",
    organId: "intestine",
    organName: "Taste Buds",
    badge: "Deep Biology",
    icon: "👅",
  },
  {
    id: "sens-72",
    headline: "Blind Spot Filled by Brain",
    fact: "Where the optic nerve exits the posterior eye (optic disc), there are zero photoreceptors. Your brain's visual cortex automatically hallucinates and interpolates missing imagery.",
    category: "Sensory & Eyes",
    organId: "eyeball",
    organName: "Optic Disc",
    badge: "Clinical Pearl",
    icon: "🪄",
  },
  {
    id: "sens-73",
    headline: "Ear's Cochlea Tunes 20,000 Frequencies",
    fact: "The spiral cochlea contains 16,000 hair cells arranged tonotopically like a piano keyboard, responding to acoustic frequencies from 20 Hz up to 20,000 Hz.",
    category: "Sensory & Eyes",
    organId: "brain",
    organName: "Organ of Corti",
    badge: "Superpower",
    icon: "🎵",
  },
  {
    id: "sens-74",
    headline: "Rods Outnumber Cones 20 to 1",
    fact: "Your retinas contain about 120 million rod cells (for monochrome night vision and peripheral motion) but only 6 million cones (concentrated in the fovea for sharp color vision).",
    category: "Sensory & Eyes",
    organId: "eyeball",
    organName: "Rods & Cones",
    badge: "Deep Biology",
    icon: "🕯️",
  },
  {
    id: "sens-75",
    headline: "Fovea: Sharp Center of Focus",
    fact: "The fovea centralis measures only 1.5 mm wide, yet it accounts for over 50% of the visual processing power that is sent to the brain's primary visual cortex.",
    category: "Sensory & Eyes",
    organId: "eyeball",
    organName: "Fovea Centralis",
    badge: "Clinical Pearl",
    icon: "🎯",
  },

  // ==================== SKIN & INTEGUMENTARY (76-85) ====================
  {
    id: "skin-76",
    headline: "Largest Organ: 20 Square Feet",
    fact: "The skin is the largest and heaviest organ in the human body, covering an area of roughly 2 square meters (22 square feet) and accounting for 15% of total body weight.",
    category: "Skin & Integumentary",
    organId: "skin",
    organName: "Epidermis & Dermis",
    badge: "Record",
    icon: "🧴",
  },
  {
    id: "skin-77",
    headline: "30,000 Dead Skin Cells Lost Every Minute",
    fact: "You shed roughly 30,000 to 40,000 dead keratinized skin cells every minute (nearly 9 pounds or 4 kg over a year), making up much of household dust.",
    category: "Skin & Integumentary",
    organId: "skin",
    organName: "Stratum Corneum",
    badge: "Fun Fact",
    icon: "✨",
  },
  {
    id: "skin-78",
    headline: "2 to 5 Million Sweat Glands",
    fact: "Your body contains between 2 and 5 million eccrine sweat glands. On hot days of heavy exertion, they can produce up to 3 liters of cooling evaporative sweat per hour.",
    category: "Skin & Integumentary",
    organId: "skin",
    organName: "Eccrine Glands",
    badge: "Record",
    icon: "💦",
  },
  {
    id: "skin-79",
    headline: "11 Miles of Blood Vessels in Skin",
    fact: "Your skin contains more than 11 miles of microvascular capillary loops that dilate or constrict to regulate systemic core body temperature.",
    category: "Skin & Integumentary",
    organId: "skin",
    organName: "Dermal Papillae",
    badge: "Deep Biology",
    icon: "🌡️",
  },
  {
    id: "skin-80",
    headline: "Fingerprints Form at 10 Weeks in Womb",
    fact: "Unique dermal friction ridges (fingerprints) form in the womb around week 10 of gestation as amniotic fluid pressure interacts with genetic growth rates—even identical twins differ.",
    category: "Skin & Integumentary",
    organId: "skin",
    organName: "Dermal Ridges",
    badge: "Mind-Blowing",
    icon: "🖐️",
  },
  {
    id: "skin-81",
    headline: "Skin Makes Vitamin D from Sunlight",
    fact: "7-dehydrocholesterol in the epidermal stratum basale absorbs UVB photons from solar radiation, converting it into cholecalciferol (Vitamin D3) to maintain bone calcium homeostasis.",
    category: "Skin & Integumentary",
    organId: "skin",
    organName: "Vitamin D Synthesis",
    badge: "Superpower",
    icon: "☀️",
  },
  {
    id: "skin-82",
    headline: "Melanin: Biological Umbrella",
    fact: "Melanocytes package melanin pigment into melanosomes and transfer them over keratinocyte nuclei like miniature sun umbrellas, absorbing DNA-damaging UV rays.",
    category: "Skin & Integumentary",
    organId: "skin",
    organName: "Melanocytes",
    badge: "Clinical Pearl",
    icon: "⛱️",
  },
  {
    id: "skin-83",
    headline: "Fingernails Grow 4x Faster Than Toenails",
    fact: "Fingernails grow at roughly 3.5 mm per month (about 4 times faster than toenails), with the nail on your dominant hand's middle finger growing the fastest.",
    category: "Skin & Integumentary",
    organId: "skin",
    organName: "Nail Matrix",
    badge: "Fun Fact",
    icon: "💅",
  },
  {
    id: "skin-84",
    headline: "Hair is Made of Same Protein as Horns",
    fact: "Human hair and fingernails are composed of dense structural alpha-keratin—the exact same insoluble structural protein found in animal hooves, claws, and rhino horns.",
    category: "Skin & Integumentary",
    organId: "skin",
    organName: "Keratin Shaft",
    badge: "Deep Biology",
    icon: "🦏",
  },
  {
    id: "skin-85",
    headline: "Goosebumps: Vestigial Thermoregulation",
    fact: "Tiny arrector pili muscles at the base of hair follicles contract during cold or fear to make hair stand up (piloerection), a vestigial trait inherited from furry mammalian ancestors.",
    category: "Skin & Integumentary",
    organId: "skin",
    organName: "Arrector Pili",
    badge: "Fun Fact",
    icon: "🥶",
  },

  // ==================== KIDNEYS & EXCRETORY (86-93) ====================
  {
    id: "kid-86",
    headline: "180 Liters Filtered Daily",
    fact: "Your two kidneys filter approximately 180 liters (48 gallons) of plasma every single day, purifying your entire blood volume roughly 30 to 40 times in 24 hours.",
    category: "Kidneys & Excretory",
    organId: "kidneys",
    organName: "Kidneys",
    badge: "Record",
    icon: "🫘",
  },
  {
    id: "kid-87",
    headline: "2 Million Microscopic Nephrons",
    fact: "Each human kidney contains roughly 1 million nephrons. If their microscopic renal tubules were uncoiled and connected, they would stretch over 5 miles (8 km).",
    category: "Kidneys & Excretory",
    organId: "kidneys",
    organName: "Nephron",
    badge: "Mind-Blowing",
    icon: "🔬",
  },
  {
    id: "kid-88",
    headline: "99% of Filtered Fluid Reabsorbed",
    fact: "Out of the 180 liters of glomerular filtrate processed daily, the renal tubules reabsorb over 99% of the water and solutes, concentrating waste into only 1.5 liters of urine.",
    category: "Kidneys & Excretory",
    organId: "kidneys",
    organName: "Loop of Henle",
    badge: "Deep Biology",
    icon: "💧",
  },
  {
    id: "kid-89",
    headline: "20% of Cardiac Output for Kidneys",
    fact: "Even though both kidneys together weigh less than 300 grams (under 0.5% of body weight), they receive 20% to 25% of all blood pumped by the heart every minute.",
    category: "Kidneys & Excretory",
    organId: "kidneys",
    organName: "Renal Arteries",
    badge: "Clinical Pearl",
    icon: "⚡",
  },
  {
    id: "kid-90",
    headline: "Kidneys Control Red Blood Cell Production",
    fact: "When renal oxygen levels drop, the kidneys secrete the hormone erythropoietin (EPO), which signals bone marrow stem cells to accelerate red blood cell synthesis.",
    category: "Kidneys & Excretory",
    organId: "kidneys",
    organName: "EPO Hormone",
    badge: "Clinical Pearl",
    icon: "🩸",
  },
  {
    id: "kid-91",
    headline: "Bladder Expands to 500 mL",
    fact: "The urinary bladder wall contains specialized transitional epithelium that stretches like an accordion, expanding from empty to holding 400–600 mL without leaking.",
    category: "Kidneys & Excretory",
    organId: "kidneys",
    organName: "Detrusor Muscle",
    badge: "Fun Fact",
    icon: "🎈",
  },
  {
    id: "kid-92",
    headline: "You Can Live with Only One Kidney",
    fact: "If one kidney is lost or donated, the remaining kidney undergoes compensatory hypertrophy, growing by up to 30% to perform 85% of normal two-kidney filtration.",
    category: "Kidneys & Excretory",
    organId: "kidneys",
    organName: "Compensatory Hypertrophy",
    badge: "Superpower",
    icon: "💖",
  },
  {
    id: "kid-93",
    headline: "Acid-Base Blood Balance Keeper",
    fact: "While the lungs control rapid pH changes by blowing off CO2, the kidneys provide long-term systemic acid-base buffer control by secreting hydrogen ions and retaining bicarbonate.",
    category: "Kidneys & Excretory",
    organId: "kidneys",
    organName: "Renal Buffering",
    badge: "Deep Biology",
    icon: "⚖️",
  },

  // ==================== BLOOD & IMMUNE SYSTEM (94-102) ====================
  {
    id: "blood-94",
    headline: "2.5 Million Red Blood Cells Every Second",
    fact: "Your red bone marrow manufactures roughly 2.5 million new erythrocytes every second (over 200 billion daily) to replace aging cells that have completed their 120-day lifespan.",
    category: "Blood & Immune",
    organId: "heart",
    organName: "Bone Marrow",
    badge: "Record",
    icon: "🩸",
  },
  {
    id: "blood-95",
    headline: "White Blood Cells Squeeze Through Solid Walls",
    fact: "Through a biological process called diapedesis, white blood cells can change shape and slip directly between endothelial capillary cells to attack infections in surrounding tissue.",
    category: "Blood & Immune",
    organId: "skin",
    organName: "Leukocytes",
    badge: "Superpower",
    icon: "🛡️",
  },
  {
    id: "blood-96",
    headline: "Hemoglobin Carries 4 Oxygen Molecules",
    fact: "A single red blood cell contains approximately 270 million hemoglobin molecules. Each hemoglobin protein binds 4 oxygen atoms, carrying over 1 billion oxygen molecules per cell.",
    category: "Blood & Immune",
    organId: "heart",
    organName: "Hemoglobin",
    badge: "Mind-Blowing",
    icon: "🫧",
  },
  {
    id: "blood-97",
    headline: "Platelets Plug Wounds in Seconds",
    fact: "Upon detecting damaged vascular collagen, circulating platelets change from smooth discs to spiky spheres, adhering together to form a primary hemostatic plug in under 60 seconds.",
    category: "Blood & Immune",
    organId: "heart",
    organName: "Thrombocytes",
    badge: "Clinical Pearl",
    icon: "🩹",
  },
  {
    id: "blood-98",
    headline: "The Spleen: Blood Filter & Bank",
    fact: "The spleen acts as the body's quality-control graveyard for old red blood cells and stores emergency reserves of up to one cup of oxygenated blood and half of your monocytes.",
    category: "Blood & Immune",
    organId: "liver",
    organName: "Spleen",
    badge: "Clinical Pearl",
    icon: "🏛️",
  },
  {
    id: "blood-99",
    headline: "Memory B-Cells Remember for 90 Years",
    fact: "Adaptive immune Memory B and T cells can survive in the bone marrow and lymph nodes for over 90 years, rapidly conferring lifetime immunity against recurring infections.",
    category: "Blood & Immune",
    organId: "skin",
    organName: "Memory B-Cells",
    badge: "Superpower",
    icon: "🧠",
  },
  {
    id: "blood-100",
    headline: "Lymphatic System Clears 3 Liters Daily",
    fact: "The lymphatic vascular network drains approximately 3 to 4 liters of excess filtered interstitial fluid from tissues daily, purifying it through hundreds of lymph nodes before returning it to veins.",
    category: "Blood & Immune",
    organId: "heart",
    organName: "Lymph Nodes",
    badge: "Deep Biology",
    icon: "💧",
  },
  {
    id: "blood-101",
    headline: "Natural Killer Cells Hunt Mutated Cancer Cells",
    fact: "Natural Killer (NK) immune cells patrol your body constantly, recognizing stressed or malignant cells that have down-regulated MHC-I molecules and destroying them with perforin enzymes.",
    category: "Blood & Immune",
    organId: "skin",
    organName: "NK Cells",
    badge: "Superpower",
    icon: "🎯",
  },
  {
    id: "blood-102",
    headline: "Blood Accounts for 7–8% of Body Weight",
    fact: "An average adult has 4.5 to 5.5 liters of blood circulating at any given time, making up approximately 7% to 8% of total body weight.",
    category: "Blood & Immune",
    organId: "heart",
    organName: "Blood Volume",
    badge: "Fun Fact",
    icon: "⚖️",
  },

  // ==================== BIOLOGICAL RECORDS & SUPERPOWERS (103-110) ====================
  {
    id: "rec-103",
    headline: "DNA Could Reach Pluto and Back",
    fact: "Each human diploid cell contains roughly 2 meters (6 feet) of tightly coiled DNA. If all DNA in your 37 trillion cells were unraveled and linked end-to-end, it would stretch twice the diameter of the Solar System.",
    category: "Records & Curiosities",
    organId: "brain",
    organName: "Chromatin",
    badge: "Mind-Blowing",
    icon: "🌌",
  },
  {
    id: "rec-104",
    headline: "Humans are Bioluminescent",
    fact: "The human body literally glows with visible light! Metabolic biochemical reactions emit ultra-weak photon emissions that are 1,000 times dimmer than the sensitivity of the human naked eye.",
    category: "Records & Curiosities",
    organId: "skin",
    organName: "Bioluminescence",
    badge: "Mind-Blowing",
    icon: "🌟",
  },
  {
    id: "rec-105",
    headline: "Heat Output Equal to a 100W Lightbulb",
    fact: "At rest, the basal metabolic rate of an adult human body generates approximately 100 joules of thermal energy per second—equivalent to the continuous heat output of a 100-watt incandescent bulb.",
    category: "Records & Curiosities",
    organId: "liver",
    organName: "Basal Metabolism",
    badge: "Fun Fact",
    icon: "💡",
  },
  {
    id: "rec-106",
    headline: "Circadian Body Temperature Dip",
    fact: "Your core body temperature naturally fluctuates by about 1°C (1.8°F) throughout 24 hours, dropping to its lowest point around 4:00 AM under suprachiasmatic nucleus control.",
    category: "Records & Curiosities",
    organId: "brain",
    organName: "Hypothalamus",
    badge: "Deep Biology",
    icon: "⏰",
  },
  {
    id: "rec-107",
    headline: "Tongue Print is as Unique as a Fingerprint",
    fact: "Just like fingerprints and iris patterns, the 3D surface topography, papillae distribution, and groove patterns on a human tongue are completely unique to each individual.",
    category: "Records & Curiosities",
    organId: "intestine",
    organName: "Tongue Anatomy",
    badge: "Fun Fact",
    icon: "👅",
  },
  {
    id: "rec-108",
    headline: "Stomach Acid Replaced by Iron-Rich Spleen",
    fact: "Your body recycles over 20 mg of elemental iron every day from degraded heme rings, ensuring your vital oxygen transport never runs dry.",
    category: "Records & Curiosities",
    organId: "liver",
    organName: "Iron Metabolism",
    badge: "Clinical Pearl",
    icon: "🧲",
  },
  {
    id: "rec-109",
    headline: "Yawning Cools Down Your Brain",
    fact: "Physiological studies suggest yawning increases facial blood flow and introduces cool inhaled ambient air, acting as a radiator to lower elevated cerebral cortex temperature.",
    category: "Records & Curiosities",
    organId: "brain",
    organName: "Brain Thermoregulation",
    badge: "Fun Fact",
    icon: "🥱",
  },
  {
    id: "rec-110",
    headline: "Every 7 Years: An Almost New You",
    fact: "Because different cells turn over at various rates (stomach in 3 days, skin in 4 weeks, red blood cells in 4 months, bones in 10 years), the vast majority of cells in your body are completely renewed over a decade.",
    category: "Records & Curiosities",
    organId: "skin",
    organName: "Cellular Turnover",
    badge: "Mind-Blowing",
    icon: "🔄",
  },
];
